#!/bin/bash
set -e

test "$ENGINE_ROOT"  || ENGINE_ROOT=$(realpath "$(dirname "$0")"/..)
test "$CONTENT_ROOT" || CONTENT_ROOT=$(realpath "$ENGINE_ROOT"/..)

ENGINE_ROOT=$(realpath "$ENGINE_ROOT")
CONTENT_ROOT=$(realpath "$CONTENT_ROOT")

. "$ENGINE_ROOT"/lib/sh/terraform-setup.sh

exec "${TERRAFORM[@]}" apply -auto-approve -var-file="$INFRA_TARGET_ENDPOINT/target.tfvars"
