name: 'Habitat: Publish Package'
description: 'Build and publish a Habitat package'
inputs:
  hab-origin-key-secret:
    description: 'Secret key for Habitat origin'
    required: true
  hab-origin-key-public:
    description: 'Public key for Habitat origin'
    required: true
  hab-auth-token:
    description: 'Personal access token for Habitat CLI'
    required: true
  checkout:
    description: 'Whether to check out the repository'
    required: false
    default: 'true'
outputs:
  pkg_origin:
    description: "Origin of built package"
    value: ${{ steps.build.outputs.pkg_origin }}
  pkg_name:
    description: "Name of built package"
    value: ${{ steps.build.outputs.pkg_name }}
  pkg_ident:
    description: "Full identifier for built package"
    value: ${{ steps.build.outputs.pkg_ident }}
  pkg_artifact:
    description: "Filename for built package archive"
    value: ${{ steps.build.outputs.pkg_artifact }}
  pkg_version:
    description: "Full version number for built package"
    value: ${{ steps.build.outputs.pkg_version }}

runs:
  using: composite
  steps:

  - name: 'Initialize Chef Habitat environment'
    uses: JarvusInnovations/habitat-action@action/v1
    with:
      deps: core/hab-plan-build

  - name: Import origin key
    shell: bash
    run: |
      hab origin key import <<END_OF_KEY
      ${{ inputs.hab-origin-key-secret }}
      END_OF_KEY

      hab origin key import <<END_OF_KEY
      ${{ inputs.hab-origin-key-public }}
      END_OF_KEY

  - uses: actions/checkout@v3
    if: ${{ inputs.checkout == 'true' }}

  - name: Build Habitat package
    id: build
    shell: bash
    run: |
      hab pkg exec core/hab-plan-build hab-plan-build .
      cat results/last_build.env >> "${GITHUB_OUTPUT}"

  - name: Upload Habitat package
    id: upload
    shell: bash
    env:
      HAB_AUTH_TOKEN: '${{ inputs.hab-auth-token }}'
    run: |
      source results/last_build.env
      hab pkg upload "results/${pkg_artifact}" -c stable
