#!/bin/bash
set -e

test "$ENGINE_ROOT"  || ENGINE_ROOT=$(realpath "$(dirname "$0")"/..)
test "$CONTENT_ROOT" || CONTENT_ROOT=$(realpath "$ENGINE_ROOT"/..)

ENGINE_ROOT=$(realpath "$ENGINE_ROOT")
CONTENT_ROOT=$(realpath "$CONTENT_ROOT")

. "$ENGINE_ROOT"/lib/sh/terraform-setup.sh

set +e
"${TERRAFORM[@]}" plan -detailed-exitcode -compact-warnings -var-file="$INFRA_TARGET_ENDPOINT/target.tfvars" "$@"
rc=$?
set -e

case $rc in
  0) exit 0;;
  1) exit 2;;
  2) exit 1;;
esac
