#!/bin/bash
set -e

ENGINE_ROOT=$(realpath "$(dirname "$0")"/..)

. "$ENGINE_ROOT"/lib/sh/terraform-setup.sh

exec "${TERRAFORM[@]}" apply -auto-approve -var-file="$INFRA_TARGET_ENDPOINT/target.tfvars"
